version: "3"

services:
    controller:
        build: ./controller
        image: controller:latest
        container_name: controller
        command: service apache2 start && service mysql start && bash
        tty: true
        cap_add: 
           - ALL
        network_mode: host
        privileged: true
        ports: 
          - 3306:3306
          - 33060:33060
          - 80:80
          - 6633:6633

    rootSwitch:
        build: ./root-switch
        image: rootswitch:latest
        container_name: rootswitch
        command: bash /local/rootSwitch_config.sh ${Controller_Public_IP}
        tty: true
        cap_add:
            - ALL
        privileged: true
        networks:
            localNet:
                ipv4_address: 172.18.0.3

    slaveSwitch:
        build: ./slave-switch
        image: slaveswitch:latest
        container_name: slaveswitch
        command: bash /local/slaveSwitch_config.sh ${Controller_Public_IP}
        tty: true
        cap_add:
            - ALL
        privileged: true
        networks:
            localNet:
                ipv4_address: 172.18.0.4

    server:
        build: ./server
        image: server:latest
        container_name: server
        command: bash /local/server_config.sh
        tty: true
        cap_add:
            - ALL
        privileged: true
        networks:
            localNet:
                ipv4_address: 172.18.0.5

    attacker:
        build: ./attacker
        image: attacker:latest
        container_name: attacker
        command: bash /local/attacker_config.sh
        tty: true
        cap_add:
            - ALL
        privileged: true
        networks:
            localNet:
                ipv4_address: 172.18.0.6

    qvm:
        build: ./qvm
        image: qvm:latest
        container_name: qvm
        command: bash /local/qvm_config.sh
        tty: true
        cap_add:
            - ALL
        privileged: true
        networks:
            localNet:
                ipv4_address: 172.18.0.7
    
    user:
        build: ./user
        image: user:latest
        container_name: user
        command: bash /local/user_config.sh
        tty: true
        cap_add:
            - ALL
        privileged: true
        networks:
            localNet:
                ipv4_address: 172.18.0.8

networks:
    localNet:
        ipam:
            config:
                - subnet: 172.18.0.0/24

