version: "3"

services:
    controller:
        build: ./controller
        image: controller:latest
        container_name: controller
        tty: true
        network_mode: host
        privileged: true
        restart: always
        ports: 
          - 3306:3306
          - 33060:33060
          - 80:80
          - 6633:6633

    rootSwitch:
        build: ./root-switch
        image: rootswitch:latest
        container_name: rootswitch
        tty: true
        restart: always
        privileged: true
        networks:
            localNet:
                ipv4_address: 172.18.0.3

    slaveSwitch:
        build: ./slave-switch
        image: slaveswitch:latest
        container_name: slaveswitch
        tty: true
        restart: always
        privileged: true
        networks:
            localNet:
                ipv4_address: 172.18.0.4

    server:
        build: ./server
        image: server:latest
        container_name: server
        restart: always
        tty: true
        privileged: true
        networks:
            localNet:
                ipv4_address: 172.18.0.5

    attacker:
        build: ./attacker
        image: attacker:latest
        container_name: attacker
        restart: always
        tty: true
        privileged: true
        networks:
            localNet:
                ipv4_address: 172.18.0.6

    qvm:
        build: ./qvm
        image: qvm:latest
        container_name: qvm
        restart: always
        tty: true
        privileged: true
        networks:
            localNet:
                ipv4_address: 172.18.0.7
    
    user:
        build: ./user
        image: user:latest
        container_name: user
        restart: always
        tty: true
        privileged: true
        networks:
            localNet:
                ipv4_address: 172.18.0.8

networks:
    localNet:
        ipam:
            config:
                - subnet: 172.18.0.0/24